export const adminAT = {
  INIT_ADMIN_IN_SYSTEM: "INIT_ADMIN_IN_SYSTEM",
  GET_ORDERS_PRODUCTS: "GET_ORDERS_PRODUCTS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  CHANGE_ITEMS_PRODUCT: "CHANGE_ITEMS_PRODUCT",
  SAVE_CHANGE_ITEMS_PRODUCT: "SAVE_CHANGE_ITEMS_PRODUCT",
  DELETE_ITEMS_PRODUCT: "DELETE_ITEMS_PRODUCT",
}
