export const loginAT = {
  LOGIN_USER: "LOGIN_USER",
  NEW_USER: "NEW_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  CLEAR_ERRORS: "CLEAR_ERRORS",
}
